# 阿里云短信配置
aliyun:
  sms:
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    sign-name: 速通互联验证码
    template-code: 100001

server:
  port: ${PORT:9999}

# 数据库配置（已替换为你的 TiDB 云数据库）
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 49yZuNgDoBVfpvs.root
    password: fu4iGqBRbn9SB77Z
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/quan?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true

  # Spring Mail 163邮箱配置
  mail:
    host: smtp.163.com
    port: 465
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.163.com
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
            fallback: false
        debug: true

mybatis:
  ## 映射xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# DeepSeek AI
deepseek:
  api-key: ${DEEPSEEK_API_KEY}  # 你的 DeepSeek 密钥

alipay:
  app-id: ${ALIPAY_APP_ID}      # 支付宝沙盒 AppID
  private-key: ${ALIPAY_PRIVATE_KEY}  # 支付宝私钥
  alipay-public-key: ${ALIPAY_PUBLIC_KEY}  # 支付宝公钥
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do  # 这个是公开地址，不用改
  notify-url: ${ALIPAY_NOTIFY_URL}  # 你的公网回调地址
  return-url: ${ALIPAY_RETURN_URL}  # 支付成功后的跳转地址
